imageURL = 'https://1.bp.blogspot.com/-
nVZ5W2j39c4/VkFf5Wh27SI/AAAAAAAAAOA/ngY9AI9C9CY/s320/hsi.png';
hsiImage = imread(imageURL);
H = double(hsiImage(:, :, 1)) * 2 * pi / 255;
S = double(hsiImage(:, :, 2)) / 255;
I = double(hsiImage(:, :, 3)) / 255;
R = zeros(size(H));
G = zeros(size(H));
B = zeros(size(H));
idx = (0 <= H) & (H < 2*pi/3);
B(idx) = I(idx) .* (1 - S(idx));
R(idx) = I(idx) .* (1 + S(idx) .* cos(H(idx)) ./ cos(pi/3 - H(idx)));
G(idx) = 3 * I(idx) - (R(idx) + B(idx));
idx = (2*pi/3 <= H) & (H < 4*pi/3);
R(idx) = I(idx) .* (1 - S(idx));
G(idx) = I(idx) .* (1 + S(idx) .* cos(H(idx) - 2*pi/3) ./ cos(pi - H(idx)));
B(idx) = 3 * I(idx) - (R(idx) + G(idx));
idx = (4*pi/3 <= H) & (H < 2*pi);
G(idx) = I(idx) .* (1 - S(idx));
B(idx) = I(idx) .* (1 + S(idx) .* cos(H(idx) - 4*pi/3) ./ cos(5*pi/3 - H(idx)));
R(idx) = 3 * I(idx) - (G(idx) + B(idx));
rgbImage = cat(3, R, G, B);
rgbImage = max(0, min(1, rgbImage));
figure;
subplot(1, 2, 1);
imshow(hsiImage);
title('HSI Image');
subplot(1, 2, 2);
imshow(rgbImage);
title('RGB Image');
