imageURL = 'https://cdnpt01.viewbug.com/media/mediafiles/2017/01/09/70755471_large.jpg';
originalImage = imread(imageURL);
filterSize = 3;
medianImage = medfilt2(originalImage, [filterSize filterSize]);
figure;
subplot(1, 2, 1);
imshow(originalImage);
title('Original Image');
subplot(1, 2, 2);
imshow(medianImage);
title('Median Filtered Image');
